blank_issues_enabled: false
contact_links:
    - name: ğŸ’¡ Features and Ideas
      url: https://github.com/outfielddigital/konstrukt/discussions
      about: Start a new discussion when you have ideas or feature requests
    - name: â‰ï¸ Support Question
      url: https://our.umbraco.com/packages/backoffice-extensions/konstrukt/konstrukt-support/
      about: If you have a question, please join us on the forum.
    - name: ğŸ“– Documentation Issue
      url: https://github.com/outfielddigital/konstrukt-documentation/issues
      about: Documentation issues should be reported on the Konstrukt documentation repository.
