blank_issues_enabled: false
contact_links:
    - name: ğŸ’¡ Features and Ideas
      url: https://github.com/umbraco/Umbraco-CMS/discussions/new?category=features-and-ideas
      about: Start a new discussion when you have ideas or feature requests, eventually discussions can turn into plans
    - name: â‰ï¸ Support Question
      url: https://our.umbraco.com/packages/backoffice-extensions/konstrukt/konstrukt-support/
      about: This issue tracker is NOT meant for support questions. If you have a question, please join us on the forum.
    - name: ğŸ“– Documentation Issue
      url: https://github.com/outfielddigital/konstrukt-documentation/issues
      about: Documentation issues should be reported on the Konstrukt documentation repository.
