blank_issues_enabled: false
contact_links:
    - name: ğŸ’¡ Features and Ideas
      url: https://github.com/umbraco/Umbraco.UIBuilder.Issues/discussions
      about: Start a new discussion when you have ideas or feature requests
    - name: â‰ï¸ Support Question
      url: mailto:support@umbraco.com
      about: If you have a question, please email Umbraco support.
    - name: ğŸ“– Documentation Issue
      url: https://github.com/umbraco/UmbracoDocs/issues
      about: Documentation issues should be reported on the Konstrukt documentation repository.
